server:
  #服务调用者端口号
  port: 50001
spring:
  application:
    name: ServerClient
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: wuyuchannel
        output:
          destination: wuyuexchannel
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      #将当前服务也注册到注册中心
      defaultZone: http://eurekaserver1:30001/eureka/
feign:
  hystrix:
    enabled: true
